excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://wietsevr.github.io
title: WietseVR
tagline: A log of everyday life
description: Read Wietse Van Ransbeeck's opinions here.<br />
paginate: 10
