excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://wietsevr.github.io
title: WietseVR
tagline: A log of everyday life
description: A millennial entrepreneur talking about startups, cities and tech.<br />
paginate: 10
