excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://wietsevr.github.io
title: WietseVR
tagline: A log of everyday life
description: Millennial entrepreneur. Art lover. Micro-journalist. Digital nomad. Urbanite.<br />
paginate: 10
